### ISSUE TITLE
Unsupported Operating System. Please add your own Selenium driver for it

### ISSUE THREAD

**Issue by LogitechGalena** [alexschimpf/Snkrs-Bot#14]
Hey, I was wondering if I could get some help with this. When I run the program I get this error:
`Traceback (most recent call last):
  File "main.py", line 253, in <module>
    raise Exception("Unsupported operating system. Please add your own Selenium driver for it.")
Exception: Unsupported operating system. Please add your own Selenium driver for it.`

Please help as I only have a couple days until the sneakers I'm trying to get release.

**Comment by WalyssonPaiva** [comment]
You need to download the webdriver for your OS and replace it (you probably use win, right !?). If u r using firefox: https://github.com/mozilla/geckodriver/releases;
if u r using chrome: https://chromedriver.chromium.org/downloads
