### ISSUE TITLE
how do I add the information and how do I activate the bot?

### ISSUE THREAD

**Issue by marcelconde** [alexschimpf/Snkrs-Bot#16]
Good afternoon! I'm having trouble using the bot, I have no experience in handling this advanced programming.
I don't know where in the code I add the information like: tennis link, tennis size, my login and my credit card. I also don't know how to run / activate the bot ... If you can explain to me how the bot works I appreciate it!

**Comment by alexschimpf** [comment]
People have been updating the README to help you out (another PR is open for this as well).
