### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by Spectrum645** [alexschimpf/Snkrs-Bot#17]
Update to Python version 3 please, Python version 2 is no longer active

**Comment by alexschimpf** [comment]
@Spectrum645 The README specifically says this script is meant to be run using Python3.7.

**Comment by Spectrum645** [comment]
> @Spectrum645 The README specifically says this script is meant to be run using Python3.7.

Aight guess I can't read then, my bad. 🤡  Thanks for letting me know!
