### ISSUE TITLE
--url <your-shoes-url>

### ISSUE THREAD

**Issue by jhwt1805** [alexschimpf/Snkrs-Bot#20]
Hi ..

firstly thanks for the good work here.

However, I run into a problem - login + pw are working fine, but the part to open the requested URL --url <your-shoes-url> does not work. Any idea (i.e. sample URL) or how can I trace/log it?

Thanks in advance
BR
J

**Comment by jhwt1805** [comment]
Resolved

**Comment by schmackz** [comment]
how did you resolve this?
