### ISSUE TITLE
No Module found 'Pause'

### ISSUE THREAD

**Issue by Gavin-marler** [alexschimpf/Snkrs-Bot#29]
Im just running 
```python
python3 main.py
```
to see if it compiles and I get the error message:
```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import pause
ModuleNotFoundError: No module named 'pause'
```
Any reason why pause wouldn't work?

**Comment by alexschimpf** [comment]
Did you install requirements.txt?

**Comment by Gavin-marler** [comment]
I did. It says that the requirements are already satisfied. It also says Python 2.7 is deprecated.

**Comment by ericruiz-developer** [comment]
Likely because it needs to be `python3 pip3 install -r requirements` 

You're likely using the `python3 main.py` command but when you just run `pip install -r requirements` you're installing dependencies for the python 2 binary.

**Comment by Gavin-marler** [comment]
I reinstalled python3 and then ran
```python 
pip3 install -r requirements.txt
```
and it showed building wheels for pause and says that pause was successfully built. Then when I run python3 main.py it shows the same error.

**Comment by schmackz** [comment]
I got it to run by just using python instead of python3

`python main.py`

**Comment by ericruiz-developer** [comment]
This all comes down to where the binaries get installed and that depends on your Python configuration or which Python you're actually using when you do the install.

**Comment by Gavin-marler** [comment]
I did get it to run using just python main.py. It was mostly user error, sorry for the inconvenience.
