### ISSUE TITLE
Run Bot Error

### ISSUE THREAD

**Issue by xXMoreWhisperXx** [alexschimpf/Snkrs-Bot#34]
bash: my shoe url : File or directory does not exist

is there any solution?

**Comment by alexschimpf** [comment]
Ok I'm gonna need more information. What is the exact command you ran? Did you fully read the README?

**Comment by xXMoreWhisperXx** [comment]
I managed to solve that problem but going on I found another one. I ran this command: python main.py --username username --password password --shoe-size 10.5 --url https://nike.com/myshoe --release-time "2020-12-8 16:00:01" --driver-type firefox --num-retries 100 --shoe-type M
and gave me this error: OSError: [Errno 8] Exec format error
anyway thanks a lot for the help

**Comment by alexschimpf** [comment]
Hmm. Seems like your OS is having problems with the Selenium driver executable. Do you get the same error when using chrome instead of firefox?

**Comment by xXMoreWhisperXx** [comment]
yes it gives me the same error
