### ISSUE TITLE
selenium driver for windows

### ISSUE THREAD

**Issue by mrfett777** [alexschimpf/Snkrs-Bot#6]
hello! can you please explain how to install selenium driver in you script? thank you!

**Comment by zem007** [comment]
@mrfett777 
For example if you are using Chrome:
1. check the version of your chrome
2. go to _http://chromedriver.storage.googleapis.com/index.html_, and download correspoding window driver version.
3. chance _line 251: executable_path = "./bin/geckodriver_linux"_ to your chrome driver saving path

maybe you also need to add the driver saving path to your computer's system path.

good luck!
