### ISSUE TITLE
do you need to remove the word after the --

### ISSUE THREAD

**Issue by Jony12505** [alexschimpf/Snkrs-Bot#75]
do you need to remove the words after the --.  -- username Mygmail@gmail.com or --Mygmail@gmail.com

**Comment by DevNoam** [comment]
You need write the args like so: --username mail@mail.com

**Comment by Jony12505** [comment]
what do I do for this  "__main__.py: error: the following arguments are required: --username Mail@mail.com, --password Password, --url https://www.nike.com/launch/t/air-jordan-6-travis-scott-su21"
