### ISSUE TITLE
Passing Arguments 

### ISSUE THREAD

**Issue by ghost** [alexschimpf/Snkrs-Bot#8]
How can I add the information? Ex. --username

**Comment by zem007** [comment]
> How can I add the information? Ex. --username

python main.py --username="Bob"

**Comment by vitorflc** [comment]
I'm getting invalid syntax all the time. Currently using Spyder. By the way, would you recommend any other like Pycharm or Google collab for the script? Real noob here guys. I see the code with shining eyes of someone that will try to learn all that in the future. lol

**Comment by vitorflc** [comment]
Just gonna leave it the output here so someone can help me when they see it

python main.py vi*****@gmail.com *******  https://www.nike.com/launch/t/dunk-low-ceramic 9.5
  File "<ipython-input-40-6ee94674c8a4>", line 1
    python main.py vi*****@gmail.com *******  https://www.nike.com/launch/t/dunk-low-ceramic 9.5
           ^
SyntaxError: invalid syntax
